#!/bin/bash
#https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/
# config.conf  devmapper

# clh
#crictl runp --runtime kata-clh pod-config.json
# fc
#crictl runp --runtime kata-fc pod-config.json

pid=`crictl runp --runtime kata pod-config.json`
cid=`crictl create $pid container-config.json pod-config.json`
crictl start $cid
crictl ps
#crictl exec -i -t 1f73f2d81bf98 ls
